competitionApp/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "competitionApp"
urlpatterns = [
    path('', views.pays, name="pays"),
    path('<str:pays>/', views.country, name="country"),
    path('<str:pays>/<str:competition>/', views.competition, name="competition"),
    path('<str:pays>/<str:competition>/<str:edition>/', views.competition_edition, name="competition_edition"),

]

fixtureApp/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "fixtureApp"
urlpatterns = [
    path('', views.home, name="home"),
    path('fixtures/test/', views.features_test, name="features_test"),
    path('fixtures/<int:year>/<int:month>/<int:day>/', views.fixtures, name="fixtures"),
    path('match/<uuid:id>/', views.match, name="match"),
]

settings/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

# def home(request):
#     if request.user.is_authenticated:
#         return redirect("home/")
#     return redirect("auth/login")


# urlpatterns = i18n_patterns(
urlpatterns = [
    path('', include('fixtureApp.urls')),
    path('pays/', include('competitionApp.urls')),
    path('team/', include('teamApp.urls')),
    path('predicition/', include('predictionApp.urls')),
    path('stats/', include('statsApp.urls')),
    path('admin/', admin.site.urls),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

statsApp/urls.py
from django.shortcuts import redirect
from django.urls import path, re_path
from . import views

app_name = "statsApp"
urlpatterns = [
    path('', views.statistiques, name="statistiques"),
    path('test/', views.statistiquestest, name="statistiquestest"),
    re_path(r"^rechercher/cote/(?P<home>\d+\.\d+)/(?P<away>\d+\.\d+)/(?P<draw>\d+\.\d+)/$", views.rechercher_cote, name="rechercher_cote"),
    re_path(r"^rechercher/ppg/(?P<home>\d+\.\d+)/(?P<away>\d+\.\d+)/$", views.rechercher_ppg, name="rechercher_ppg"),
    re_path(r"graphtest", views.test, name="graphtest"),
]

teamApp/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "teamApp"
urlpatterns = [
    path('<str:name>/', views.team, name="team"),
    path('<str:name>/<str:edition>/', views.team_edition, name="team_edition"),
]

templates/layout/partials/css_import.html
{% load static %} 
{% load i18n %}     
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">


<!-- Text spinners style -->
<link href="{% static 'css/plugins/textSpinners/spinners.css' %}" rel="stylesheet">

<link href="{% static 'css/plugins/chartist/chartist.min.css' %}" rel="stylesheet">

<link href="{% static 'css/animate.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

<link href="{% static 'css/plugins/iCheck/custom.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/chosen/bootstrap-chosen.css' %}" rel="stylesheet">
<link href="{% static 'js/plugins/select2/dist/css/select2.css' %}" rel="stylesheet">
<link href="{% static 'js/plugins/alerty/dist/css/alerty.min.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/ionRangeSlider/ion.rangeSlider.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/ionRangeSlider/ion.rangeSlider.skinFlat.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/datapicker/datepicker3.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/switchery/switchery.css' %}" rel="stylesheet">

<link href="{% static 'css/plugins/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet">

<!-- FooTable -->
<link href="{% static 'css/plugins/footable/footable.core.css' %}" rel="stylesheet">

<!-- FooTable -->
<link href="{% static 'css/plugins/chosen/bootstrap-chosen.css' %}" rel="stylesheet">


<link href="{% static 'css/general.css' %}" rel="stylesheet">


<!-- feuille de style de Shamman -->
{% comment %} <link rel="stylesheet" type="text/css" href="{% static 'shamman/shamman.css' %}"> {% endcomment %}

templates/layout/partials/footer.html
{% load static %}
{% load i18n %}


<div class="footer">
  <div>
    {% translate "Copyright" %} &copy; 2022 - {% now "Y" %} | {% translate "By" %}<strong>Copyright</strong> Wikibet &copy;
  </div>
  <div class="pull-right">
      10GB of <strong>250GB</strong> Free.
  </div>
</div>

templates/layout/partials/header.html
{% load static %} 
{% load i18n %}


<nav class="navbar navbar-wrapper navbar-fixed-top navbar-static-top" role="navigation">
    <div class="navbar-header ">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <i class="fa fa-reorder"></i>
        </button>
        <a href="{% url 'fixtureApp:home' %}" class="navbar-brand">Wikibet</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
        <ul class="nav navbar-nav">
            <li class="active">
                <a aria-expanded="false" role="button" href="{% url 'competitionApp:pays' %}"><i class="fa fa-sign-out"></i>Toutes les compétitions</a>
            </li>
            <li class="">
                <a aria-expanded="false" role="button" href="#" data-toggle="modal" data-target="#modal-recherche"><i class="fa fa-sign-out"></i>Rechercher</a>
            </li>
            <li class="">
                <a aria-expanded="false" role="button" href="#"><i class="fa fa-sign-out"></i>Prédictions du jour</a>
            </li>
            <li class="">
                <a aria-expanded="false" role="button" href="{% url 'statsApp:statistiques' %}"><i class="fa fa-sign-out"></i>Statistiques</a>
            </li>
            <li class="">
                <a aria-expanded="false" role="button" href="{% url 'statsApp:statistiquestest' %}"><i class="fa fa-sign-out"></i>Statistiques test</a>
            </li>
            <li class="">
                <a aria-expanded="false" role="button" href="{% url 'fixtureApp:features_test' %}"><i class="fa fa-sign-out"></i>Feture test</a>
            </li>

            <li class="dropdown">
                <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="">Menu item</a></li>
                    <li><a href="">Menu item</a></li>
                    <li><a href="">Menu item</a></li>
                    <li><a href="">Menu item</a></li>
                </ul>
            </li>

        </ul>
        <ul class="nav navbar-top-links navbar-right">

            <li>Aristide Manyessé</li>
            <li>
                <a href="login.html">
                    <i class="fa fa-sign-out"></i> Conexion
                </a>
            </li>
        </ul>
    </div>
</nav>




<div class="modal inmodal fade" id="modal-recherche" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Recherche & Filtres</h4>
                <small class="font-bold">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small>
            </div>
            <div class="modal-body">
               
                <div class="row">
                    <div class="col-sm-7">
                        <form id="form-cote" >
                            <h2 class="bold text-center">Par cotes similaires</h2><br>
                            <div class="row text-center">
                                <div class="col-sm-4">
                                    <label>Domicile</label>
                                    <input type="number" class="form-control" name="domicile" placeholder="2.01" step="0.01" required >
                                </div>
                                <div class="col-sm-4">
                                    <label>Nul</label>
                                    <input type="number" class="form-control" name="nul" placeholder="2.78" step="0.01" required >
                                </div>
                                <div class="col-sm-4">
                                    <label>Extérieur</label>
                                    <input type="number" class="form-control" name="exterieur" placeholder="2.01" step="0.01" required >
                                </div>
                            </div><br> 
                            <div class="text-center">
                                <button class="btn btn-md btn-info dim">Rechercher par cotes similaires</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-5 border-left">
                        <form id="form-ppg" >
                            <h2 class="bold text-center">Par PPG</h2><br>
                            <div class="row text-center">
                                <div class="col-sm-6">
                                    <label>Domicile</label>
                                    <input type="number" class="form-control" name="domicile" placeholder="2.01" step="0.01" required >
                                </div>
                                <div class="col-sm-6">
                                    <label>Extérieur</label>
                                    <input type="number" class="form-control" name="exterieur" placeholder="3.71" step="0.01" required >
                                </div>
                            </div><br>
                            <div class="text-center">
                                <button class="btn btn-sm btn-warning dim">Rechercher par PPG</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

templates/layout/partials/js_import.html
{% load static %} 
{% load i18n %}    
    
    <!-- Mainly scripts -->
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plotly-2.18.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

    <!-- Flot -->
    <script type="text/javascript" src="{% static 'js/plugins/flot/jquery.flot.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/flot/jquery.flot.spline.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/flot/jquery.flot.resize.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/flot/jquery.flot.pie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/flot/jquery.flot.symbol.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/flot/jquery.flot.time.js' %}"></script>


    <script type="text/javascript" src="{% static 'js/inspinia.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
    <!-- ChartJS-->
    <script type="text/javascript" src="{% static 'js/plugins/chartJs/Chart.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/chartist/chartist.min.js' %}"></script>
    <!-- Sparkline -->
    <script type="text/javascript" src="{% static 'js/plugins/sparkline/jquery.sparkline.min.js' %}"></script>
    <!-- Toastr -->
    <script type="text/javascript" src="{% static 'js/plugins/toastr/toastr.min.js' %}"></script>   <!-- Footable -->
    <script type="text/javascript" src="{% static 'js/plugins/footable/footable.all.min.js' %}"></script>
    <!-- IonRangeSlider -->
    <script type="text/javascript" src="{% static 'js/plugins/ionRangeSlider/ion.rangeSlider.min.js' %}"></script>

    <!-- Input Mask-->
    <script type="text/javascript" src="{% static 'js/plugins/jasny/jasny-bootstrap.min.js' %}"></script>

    <!-- Date range use moment.js same as full calendar plugin -->
    <script type="text/javascript" src="{% static 'js/plugins/fullcalendar/moment.min.js' %}"></script>

    <!-- Data picker -->
    <script type="text/javascript" src="{% static 'js/plugins/datapicker/bootstrap-datepicker.js' %}"></script>

    <!-- Date range picker -->
    <script type="text/javascript" src="{% static 'js/plugins/daterangepicker/daterangepicker.js' %}"></script>


    <!-- mansory -->
    <script type="text/javascript" src="{% static 'js/plugins/masonary/masonry.pkgd.min.js' %}"></script>

    <!-- datatables -->
    <script src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>
    <script src="{% static 'js/plugins/dataTables/dataTables.bootstrap4.min.js' %}" ></script>

    <!-- iCheck -->
    <script src="{% static 'js/plugins/iCheck/icheck.min.js' %}"></script>


     <!-- idle-timer -->
    <script src="{% static 'js/plugins/idle-timer/idle-timer.min.js' %}"></script>

    <!-- Select2 -->
    <script src="{% static 'js/plugins/select2/dist/js/select2.js' %}"></script>
    <script src="{% static 'js/plugins/alerty/alerty.min.js' %}"></script>
    <script src="{% static 'js/plugins/switchery/switchery.js' %}"></script>


    <script src="{% static 'js/general.js' %}"></script>

    <!-- script pour mon alerter.js -->
    {% comment %} <script type="text/javascript" src="{% static 'shamman/functions.js' %}"></script>
    <script type="text/javascript" src="{% static 'shamman/loader.js' %}"></script>
    <script type="text/javascript" src="{% static 'shamman/alerter.js' %}"></script>
    <script type="text/javascript" src="{% static 'shamman/general.js' %}"></script>
    <script type="text/javascript" src="{% static 'shamman/horloge.js' %}"></script>
    <script type="text/javascript" src="{% static 'shamman/traitement.js' %}"></script> {% endcomment %}
    

    <!-- Sparkline demo data  -->
    <script src="{% static 'js/demo/sparkline-demo.js' %}"></script>

templates/layout/partials/meta.html
{% load static %} 
{% load i18n %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="#">
<meta name="keywords" content="Application de gestion des metiers d'une briqueterie industrielle">
<meta name="author" content="Aristide Manyessé">
<link rel="icon" href="{%  static 'images/icons/favicon.ico' %}" type="image/x-icon">
<title>{{ title }}</title>    