competitionApp/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "competitionApp"
urlpatterns = [
    path('', views.pays, name="pays"),
    path('<str:pays>/', views.country, name="country"),
    path('<str:pays>/<str:competition>/', views.competition, name="competition"),
    path('<str:pays>/<str:competition>/<str:edition>/', views.competition_edition, name="competition_edition"),

]

fixtureApp/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "fixtureApp"
urlpatterns = [
    path('', views.home, name="home"),
    path('fixtures/test/', views.features_test, name="features_test"),
    path('fixtures/<int:year>/<int:month>/<int:day>/', views.fixtures, name="fixtures"),
    path('match/<uuid:id>/', views.match, name="match"),
]

predictionApp/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "features"
urlpatterns = [
    path('', views.home, name="home"),
    path('pays/', views.pays, name="pays"),
    path('pays/<str:pays>/', views.country, name="country"),
    path('pays/<str:pays>/<str:competition>/', views.competition, name="competition"),
    path('pays/<str:pays>/<str:competition>/<str:edition>/', views.competition_edition, name="competition_edition"),
    path('team/<str:name>/', views.team, name="team"),
    path('team/<str:name>/<str:edition>/', views.team_edition, name="team_edition"),
    path('match/<uuid:id>/', views.match, name="match"),
    
    
    path('stats/', views.stats, name="stats"),
    path('predictions/', views.predictions, name="predictions"),
    path('forum/', views.forum, name="forum"),


    # path('ajax/crediter/', ajax.crediter),
    # path('ajax/rembourser/', ajax.rembourser),
    # path('ajax/regler_toutes_dettes/', ajax.regler_toutes_dettes),
]

settings/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

# def home(request):
#     if request.user.is_authenticated:
#         return redirect("home/")
#     return redirect("auth/login")


# urlpatterns = i18n_patterns(
urlpatterns = [
    path('', include('fixtureApp.urls')),
    path('pays/', include('competitionApp.urls')),
    path('team/', include('teamApp.urls')),
    path('predicition/', include('predictionApp.urls')),
    path('stats/', include('statsApp.urls')),
    path('admin/', admin.site.urls),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teamApp/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "teamApp"
urlpatterns = [
    path('<str:name>/', views.team, name="team"),
    path('<str:name>/<str:edition>/', views.team_edition, name="team_edition"),
]

fixtureApp/routes.py
from .schemas import *
import graphene


class fixtureAppQuery(object):
    search_match                   = MatchType.ListField(action=graphene.String(default_value="search_match"))
    search_goal       = GoalType.ListField(action=graphene.String(default_value="search_goal"))

    
class fixtureAppMutation(object):
    create_match               = MatchType.CreateField()
    update_match               = MatchType.UpdateField()
    
    create_goal   = GoalType.CreateField()
    update_goal   = GoalType.UpdateField()

fixtureApp/views.py
from django.shortcuts import render, redirect, reverse
from django.shortcuts import get_object_or_404
from annoying.decorators import render_to
from django.http import HttpResponseRedirect
from .models import *
from datetime import datetime, timedelta
from coreApp.functions import *
from predictionApp.models import *
from competitionApp.models import *
# Create your views here.

class Score:
    score = ""
    home = 0
    away = 0
    total = 0
    proba = 0
    
    def __init__(self, home, away, c) -> None:
        self.score = f"{home}-{away}"
        self.home = home
        self.away = away
        self.total = home + away
        self.proba = c
        
    def __str__(self) -> str:
        return self.score + "---" + self.proba
    

@render_to('fixtureApp/index.html')
def home(request):
    if request.method == "GET":
        date = datetime.now()
        return HttpResponseRedirect(reverse('fixtureApp:fixtures', args=[date.year, date.month, date.day]))
        

@render_to('fixtureApp/index.html')
def fixtures(request, year, month, day):
    # Match.objects.filter(created_at__gte = datetime.today() - timedelta(days=20)).update(is_compared = False)
    # Team.objects.filter(created_at__gte = datetime.today() - timedelta(days=3)).delete()
    # Ranking.objects.filter(date__gte = datetime.today() - timedelta(days=30)).update(deleted = True)
    if request.method == "GET":
        datas = Prediction.objects.filter(is_checked = None)
        for predict in datas:
            predict.validity()
            
        date = datetime(year, month, day).date()
        datas = {}
        for edition in EditionCompetition.objects.filter(start_date__lte = date, finish_date__gte = date):
            matchs = Match.objects.filter(date = date, edition = edition)
            if len(matchs) > 0 :
                datas[edition] = matchs
        
        today = datetime.now().date()
        ctx = {
            "av_hier"     : today - timedelta(days=2),
            "hier"        : today - timedelta(days=1),
            "date"        : date,
            "today"        : today,
            "demain"      : today + timedelta(days=1),
            "ap_demain"   : today + timedelta(days=2),
            "datas"       : datas,
        }
        return ctx
        
        

@render_to('fixtureApp/match.html')
def match(request, id):
    if request.method == "GET":
        match = Match.objects.get(id=id)
        predictions = match.prediction_match.filter()
        scores = match.predictionscore_match.filter()
        
        home_last_matchs = match.home.get_last_matchs(match, number = 10, edition = True)
        home_last_forms = match.home.get_last_form(match, number = 5, edition = True)
        
        away_last_matchs = match.away.get_last_matchs(match, number = 10, edition = True)
        away_last_forms = match.away.get_last_form(match, number = 5, edition = True)
        
        home_facts = match.match_facts.filter(team = match.home)
        away_facts = match.match_facts.filter(team = match.away)
        
        stats_home = match.get_home_before_stats()
        stats_away = match.get_away_before_stats()
        
        confrontations        = Match.objects.filter(deleted = False, id__in = eval(stats_home.list_confrontations)).order_by("-date")
        similaires_ppg        = Match.objects.filter(deleted = False, id__in = eval(stats_home.list_similaires_ppg)).order_by("-date")
        similaires_ppg2       = Match.objects.filter(deleted = False, id__in = eval(stats_home.list_similaires_ppg2)).order_by("-date")
        similaires_betting    = Match.objects.filter(deleted = False, id__in = eval(stats_home.list_similaires_betting)).order_by("-date")
        list_intercepts       = Match.objects.filter(deleted = False, id__in = eval(stats_home.list_intercepts)).order_by("-date")
        
        home_rank = LigneRanking.objects.filter(team = match.home, ranking__date__lte = match.date, deleted = False, ranking__deleted = False).order_by('-ranking__date').first()
        away_rank = LigneRanking.objects.filter(team = match.away, ranking__date__lte = match.date, deleted = False, ranking__deleted = False).order_by('-ranking__date').first()
        
        home_profile = match.match_profile.filter(team = match.home).order_by('-created_at').first()
        away_profile = match.match_profile.filter(team = match.away).order_by('-created_at').first()
                
        rank = match.edition.edition_rankings.filter(date__lte = match.date).order_by('-date').first()
        competitionstats = match.edition.edition_stats.filter(ranking__date__lte = match.date).order_by('-created_at').first()
        extra_infos = match.get_extra_info_match()
        

        ctx = {
            "match"                 : match,
            "confrontations"        : confrontations[:10],
            "similaires_ppg"        : similaires_ppg,
            "similaires_ppg2"       : similaires_ppg2,
            "similaires_betting"    : similaires_betting,
            "list_intercepts"       : list_intercepts,
            "predictions"           : predictions,
            "scores"                : scores,
            "home_last_matchs"      : home_last_matchs,
            "home_last_forms"       : home_last_forms,
            "away_last_matchs"      : away_last_matchs,
            "away_last_forms"       : away_last_forms,
            "home_facts"            : home_facts,
            "away_facts"            : away_facts,
            "extra_infos"           : extra_infos,
            "rank"                  : rank,
            "home_rank"             : home_rank,
            "away_rank"             : away_rank,
            "home_profile"          : home_profile,
            "away_profile"          : away_profile,
            "stats_home"            : stats_home,
            "stats_away"            : stats_away,
            "competitionstats"      : competitionstats,
        }
        return ctx






@render_to('fixtureApp/index_test.html')
def features_test(request, ):
    if request.method == "GET":
        # type = TypePrediction.get("1X")
        type = TypePrediction.get("p0_5_MT")
        datas = PredictionTest.objects.filter(is_checked = False, type = type).values_list('match__id')
        matchs = Match.objects.filter(id__in = datas)
        
        ctx = {
            "matchs" : matchs,
        }
        return ctx
    

fixtureApp/templates/fixtureApp/index.html
{% extends "layout/base.html" %} 
{% load static %}
{% load humanize %}
{% load myfilters %}


{% block main  %}

<div class="container" >
    <div class="ibox" >
        <div class="ibox-content" style="height:250px; background-image: url('{% static "images/dist/ban-index.png" %}'); background-size: contain; ">

        </div>
    </div>
</div>


<div class="container">
    <div class="justify">

        
        <div class="input-group date ">
            <button class="btn btn-default dim btn-md-dim m-r-sm" type="button">
                <h1 class="no-margins"><i class="fa fa-calendar"></i></h1>
                <small class="text-subtitle">choisir</small>
            </button>
            <span class=""><input type="hidden" name="date" class="form-control input-group-addon" value="{{date.day|start0}}/{{date.month|start0}}/{{date.year}}"></span>
        </div>
    
        <a class="no-link" href="{% url 'fixtureApp:fixtures' av_hier.year av_hier.month av_hier.day %}">
            <button class="btn btn-{% if av_hier == date %}primary{% else %}default{% endif %} dim btn-md-dim m-r-sm" type="button">
                <h1 class="no-margins">{{av_hier.day|start0}}</h1>
                <small class="text-subtitle">Fev</small>
            </button>
        </a>

        <a class="no-link" href="{% url 'fixtureApp:fixtures' hier.year hier.month hier.day %}">
            <button class="btn btn-{% if hier == date %}primary{% else %}default{% endif %} dim btn-md-dim m-r-sm" type="button">
                <h1 class="no-margins">{{hier.day|start0}}</h1>
                <small class="text-subtitle">Fev</small>
            </button>
        </a>

        <a class="no-link" href="{% url 'fixtureApp:fixtures' today.year today.month today.day %}">
            <button class="btn btn-{% if today == date %}primary{% else %}default{% endif %} dim btn-md-dim m-r-sm" type="button">
                <h1 class="no-margins">{{today.day|start0}}</h1>
                <small class="text-subtitle">Aujourd'hui</small>
            </button>
        </a>

        <a class="no-link" href="{% url 'fixtureApp:fixtures' demain.year demain.month demain.day %}">
            <button class="btn btn-{% if demain == date %}primary{% else %}default{% endif %} dim btn-md-dim m-r-sm" type="button">
                <h1 class="no-margins">{{demain.day|start0}}</h1>
                <small class="text-subtitle">Fev</small>
            </button>
        </a>
    
        <a class="no-link" href="{% url 'fixtureApp:fixtures' ap_demain.year ap_demain.month ap_demain.day %}">
            <button class="btn btn-{% if ap_demain == date %}primary{% else %}default{% endif %} dim btn-md-dim m-r-sm" type="button">
                <h1 class="no-margins">{{ap_demain.day|start0}}</h1>
                <small class="text-subtitle">Fev</small>
            </button>
        </a>

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Nouveaux matchs <small class="m-l-sm">...</small></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                 
                    <table class="table  table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th class="text-left" colspan="3">Prédictions</th>
                                <th class="text-right" colspan="2">Domicile</th>
                                <th  width="50px" class="text-center">Score</th>
                                <th class="text-left" colspan="2">Extérieur</th>
                                <th class="text-left" colspan="3">Cotes Bet365</th>
                                <th></th>
                            </tr>
                        </thead>
                        {% for edition in datas %}
                        <tbody style="margin-top:15%">
                                <tr>
                                    <td colspan="13" class="bold">
                                        {% if edition.competition.pays.flag %}
                                            <img alt="image" style="height:20px; display:inline-block; margin-right:1%" class="img-responsive" src="{{ edition.competition.pays.flag.url }}">
                                        {% endif %}
                                        <a class="no-link" href="{% url 'competitionApp:competition_edition' edition.competition.pays edition.competition edition.edition %}">{{edition.competition.pays}} - {{edition.competition}}</a>
                                    </td>
                                </tr>
                                {% for match in datas|dict_value:edition %}
                                    {% with match.get_result as result %}
                                    <tr>
                                        <td >{{match.date | naturalday}} {{match.hour}}</td>
                                        <td class="text-left" style="width: 25%" colspan="3">
                                            {% for pre in match.predictiontest_match.filter %}
                                                <label class="m-b-md d-block label label-{% if pre.is_checked %}primary{% elif pre.is_checked == None %}default{% else %}danger{% endif %}">{{ pre.type.name }}</label>
                                            {% endfor %}
                                            {% for score in match.predictionscore_match.filter %}
                                                <label class="m-b-md d-block label label-{% if score.is_checked %}primary{% elif score.is_checked == None %}default{% else %}danger{% endif %}">{{ score.home_score }} - {{ score.away_score }}  :  {{ score.pct|rounded }}</label>
                                            {% endfor %}
                                        </td>
                                        <td class="{% if result.home_score > result.away_score %}bold{% endif %} text-right"><a class="no-link" href="{% url 'teamApp:team' match.home %}">{{match.home}}</a></td>
                                        <td class="text-right" width="10px"><label class="label label-{{ match.get_home_before_stats.ppg | couleur }}">{{ match.get_home_before_stats.ppg }}</label></td>
                                        {% if match.is_finished %}
                                        <td class="text-center">
                                            {% if result.home_half_score is not None %}
                                                <h6 class="no-margins text-center">{{result.home_half_score}} - {{result.away_half_score}}</h6>
                                            {% endif %}
                                            <p class="no-margins text-center text-small">{{result.home_score}} - {{result.away_score}}</p>
                                        </td>
                                        {% else %}
                                        <td class="text-center">
                                            <h4 class="no-margins text-center">Vs</h4>
                                        </td>
                                        {% endif %}
                                        <td class="text-left" width="10px"><label class="label label-{{ match.get_away_before_stats.ppg | couleur }}">{{ match.get_away_before_stats.ppg }}</label></td>
                                        <td class="{% if result.home_score < result.away_score %}bold{% endif %} text-left"><a class="no-link" href="{% url 'teamApp:team' match.away %}">{{match.away}}</a></td>
                                        <td class="text-left"   colspan="3">
                                            <label class="label label-{% if match.is_finished and result.home_score > result.away_score %}primary{% else %}default{% endif %}">{{ match.get_odds.home }}</label>
                                            <label class="label label-{% if match.is_finished and result.home_score == result.away_score %}primary{% else %}default{% endif %}">{{ match.get_odds.draw }}</label>
                                            <label class="label label-{% if match.is_finished and result.home_score < result.away_score %}primary{% else %}default{% endif %}">{{ match.get_odds.away }}</label>
                                        </td>
                                        <td><a target="_blank" href="{% url 'fixtureApp:match' match.id %}"><i class="fa fa-eye"></i> stats</a></td>
                                    </tr>
                                    {% endwith %}
                                {% endfor %}
                            </tbody>
                            {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




    <style>
        .bold{
            font-weight:bold;
        }
    
        .no-link{
            color: inherit;
            text-decoration: none;
        }
    </style>


    <script>
    </script>
    
    {% endblock main %}
    
    

{% block script %}

{% include "./index.js" %}

{% endblock script %}

fixtureApp/templates/fixtureApp/index_test.html
{% extends "layout/base.html" %} 
{% load static %}
{% load humanize %}
{% load myfilters %}


{% block main  %}

<div class="container" >
    <div class="ibox" >
        <div class="ibox-content" style="height:250px; background-image: url('{% static "images/dist/ban-index.png" %}'); background-size: contain; ">

        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Nouveaux matchs <small class="m-l-sm">...</small></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                 
                    <table class="table  table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th class="text-left" colspan="3">Prédictions</th>
                                <th class="text-right" ></th>
                                <th class="text-right" colspan="2">Domicile</th>
                                <th  width="50px" class="text-center">Score</th>
                                <th class="text-left" colspan="2">Extérieur</th>
                                <th class="text-right" ></th>
                                <th class="text-left" colspan="3">Cotes Bet365</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody style="margin-top:15%">
                            {% for match in matchs %}
                                {% with match.get_result as result %}
                                    {% with match.get_home_before_stats as stat_home and match.get_away_before_stats as stat_away %}
                                    <tr>
                                        <td >{{match.date}} {{match.hour}}</td>
                                        <td class="text-left" style="width: 25%" colspan="3">
                                            {% for pre in match.predictiontest_match.filter %}
                                                <label class="m-b-md d-block label label-{% if pre.is_checked %}primary{% elif pre.is_checked == None %}default{% else %}danger{% endif %}">{{ pre.type.name }}</label>
                                            {% endfor %}
                                            {% for score in match.predictionscore_match.filter %}
                                                <label class="m-b-md d-block label label-{% if score.is_checked %}primary{% elif score.is_checked == None %}default{% else %}danger{% endif %}">{{ score.home_score }} - {{ score.away_score }}</label>
                                            {% endfor %}
                                        </td>
                                        <td>{{ stat_home.points|rounded }}</td>
                                        <td class="{% if result.home_score > result.away_score %}bold{% endif %} text-right"><a class="no-link" href="{% url 'teamApp:team' match.home %}">{{match.home}}</a></td>
                                        <td class="text-right" width="10px"><label class="label label-{{ match.get_home_before_stats.ppg | couleur }}">{{ match.get_home_before_stats.ppg }}</label></td>
                                        {% if match.is_finished %}
                                        <td class="text-center">
                                            {% if result.home_half_score is not None %}
                                                <h6 class="no-margins text-center">{{result.home_half_score}} - {{result.away_half_score}}</h6>
                                            {% endif %}
                                            <p class="no-margins text-center text-small">{{result.home_score}} - {{result.away_score}}</p>
                                        </td>
                                        {% else %}
                                        <td class="text-center">
                                            <h4 class="no-margins text-center">Vs</h4>
                                        </td>
                                        {% endif %}
                                        <td class="text-left" width="10px"><label class="label label-{{ match.get_away_before_stats.ppg | couleur }}">{{ match.get_away_before_stats.ppg }}</label></td>
                                        <td class="{% if result.home_score < result.away_score %}bold{% endif %} text-left"><a class="no-link" href="{% url 'teamApp:team' match.away %}">{{match.away}}</a></td>
                                        <td>{{ stat_away.points|rounded }}</td>
                                        <td class="text-left"   colspan="3">
                                            <label class="label label-{% if match.is_finished and result.home_score > result.away_score %}primary{% else %}default{% endif %}">{{ match.get_odds.home }}</label>
                                            <label class="label label-{% if match.is_finished and result.home_score == result.away_score %}primary{% else %}default{% endif %}">{{ match.get_odds.draw }}</label>
                                            <label class="label label-{% if match.is_finished and result.home_score < result.away_score %}primary{% else %}default{% endif %}">{{ match.get_odds.away }}</label>
                                        </td>
                                        <td><a target="_blank" href="{% url 'fixtureApp:match' match.id %}"><i class="fa fa-eye"></i> stats</a></td>
                                    </tr>
                                    {% endwith %}
                                {% endwith %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




    <style>
        .bold{
            font-weight:bold;
        }
    
        .no-link{
            color: inherit;
            text-decoration: none;
        }
    </style>


    <script>
    </script>
    
    {% endblock main %}
    
    

{% block script %}

{% include "./index.js" %}

{% endblock script %}

fixtureApp/templates/fixtureApp/pays.html
{% extends "layout/base.html" %} 
{% load static %}


{% block main  %}

<div class="container">

    <div class="row">
        {% for country in  pays %}
        <div class="col-lg-4">
            <div class="contact-box">
                <a href=# data-toggle="modal" data-target="#modal-{{ country.name }}" href="{% url 'features:country' country.name %}">
                <div class="col-sm-4">
                    <div class="text-center">
                        <img alt="image" class="img-responsive" src="{% static country.flag %}">
                    </div>
                </div>
                <div class="col-sm-8">
                    <h3><strong>{{ country.name }}</strong></h3>
                    <address>
                        <h5>{{ country.pays_de_competition.filter | length }} compétition(s)</h5>
                    </address>
                </div>
                <div class="clearfix"></div>
                    </a>
            </div>
        </div>

        <div class="modal inmodal" id="modal-{{ country.name }}" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg mt-5">
                <div class="modal-content animated fadeIn">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title">Compétitions - {{ country.name }} </h4>
                        <small class="font-bold">Veuillez choisir la compétion que vous voulez voir </small>
                    </div>
                    <div class="modal-body">
                        
                        <div class="row justify-content-center">
                            {% for compet in  country.pays_de_competition.filter %}
                                <div class="col-sm-6 col-md-4 text-center border" style=" border: 1px solid red">
                                    <a href="{% url 'features:competition' country.name compet.name %}">
                                        <img alt="image" class="img-responsive" src="{% static compet.logo %}" style="height: 200px; width: 200px; border: 1px solid red">
                                        <h2>{{ compet.name }}</h2>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>

        {% endfor %}


    </div>

</div>
    
{% endblock main %}