competitionApp/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "competitionApp"
urlpatterns = [
    path('', views.pays, name="pays"),
    path('<str:pays>/', views.country, name="country"),
    path('<str:pays>/<str:competition>/', views.competition, name="competition"),
    path('<str:pays>/<str:competition>/<str:edition>/', views.competition_edition, name="competition_edition"),

]

settings/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

# def home(request):
#     if request.user.is_authenticated:
#         return redirect("home/")
#     return redirect("auth/login")


# urlpatterns = i18n_patterns(
urlpatterns = [
    path('', include('fixtureApp.urls')),
    path('pays/', include('competitionApp.urls')),
    path('team/', include('teamApp.urls')),
    path('predicition/', include('predictionApp.urls')),
    path('stats/', include('statsApp.urls')),
    path('admin/', admin.site.urls),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teamApp/urls.py
from django.shortcuts import redirect
from django.urls import path

from . import views

app_name = "teamApp"
urlpatterns = [
    path('<str:name>/', views.team, name="team"),
    path('<str:name>/<str:edition>/', views.team_edition, name="team_edition"),
]

competitionApp/models.py
from django.db import models
from django.db.models import  Q
from coreApp.models import BaseModel
from coreApp.functions import *
from fixtureApp.models import *
from bettingApp.models import *
from teamApp.models import *
import numpy as np

class Pays(BaseModel):
    code    = models.CharField(max_length = 255, null = True, blank=True)
    name    = models.CharField(max_length = 255, null = True, blank=True)
    abr     = models.CharField(max_length = 255, null = True, blank=True)
    flag    = models.ImageField(max_length = 255, upload_to = "images/pays/", default='images/pays/default.png', null = True, blank=True)

    class Meta:
        ordering = ['name']


class TypeCompetition(BaseModel):
    FULL = "FULL"
    PARTIAL = "PARTIAL"
    
    name        = models.CharField(max_length = 255, null = True, blank=True)
    etiquette   = models.CharField(max_length = 255, null = True, blank=True)
        

class Competition(BaseModel):
    identifiant   = models.CharField(max_length = 255, default="", null = True, blank=True)
    name          = models.CharField(max_length = 255, default="", null = True, blank=True)
    code          = models.CharField(max_length = 255, default="", null = True, blank=True)
    pays          = models.ForeignKey(Pays, on_delete = models.CASCADE, null = True, blank=True, related_name="pays_de_competition")
    logo          = models.ImageField(max_length = 255, upload_to = "images/competitions/", default='images/competitions/default.png', null = True, blank=True)
    type          = models.ForeignKey(TypeCompetition, on_delete = models.CASCADE, null = True, blank=True, related_name="type_de_competition")
    
    class Meta:
        ordering = ["type__etiquette", "pays", 'name']
        
    def __str__(self):
        return self.name


class Edition(BaseModel):
    name          = models.CharField(max_length = 255, null = True, blank=True)
    
    class Meta:
        ordering = ['-name']
        
    def next(self):
        if len(self.name) > 5:
            t = self.name.split("-")
            return "{}-{}".format(int(t[0])+1, int(t[1])+1)
        else:
            return "{}".format(int(self.name)+1)
        
        
        

class EditionCompetition(BaseModel):
    edition       = models.ForeignKey(Edition, on_delete = models.CASCADE, related_name="edition_team")
    competition   = models.ForeignKey(Competition, on_delete = models.CASCADE, related_name="competition_edition")
    start_date    = models.DateField(null = True, blank=True)
    finish_date   = models.DateField(null = True, blank=True)
    is_finished   = models.BooleanField(default=False, null = True, blank=True)

    class Meta:
        ordering = ["competition", '-start_date']

    def __str__(self):
        return str(self.competition) +" @ "+ str(self.edition)


    def pays(self):
        return str(self.competition.pays)
    
    def total(self):
        return str(self.edition_du_match.filter().count())
    
    
    def classement(self, date):
        try :
            datas = []
            for team in self.edition_team.filter():
                cs , btts , ga , gs = 0, 0, 0, 0
                win , draw , lose = 0, 0, 0
                matchs = Match.objects.filter(is_finished = True, is_posted = False, date__lt = date).filter(Q(home = team) | Q(away = team)).order_by("-date")
                if len(matchs) > 0:
                    for match in matchs:
                        try:
                            result = match.get_result()
                            if result is not None:
                                btts += 1 if (result.home_score > 0 and result.away_score > 0)  else 0
                                if match.home == team:
                                    gs += result.home_score
                                    ga += result.away_score
                                    cs += 1 if result.away_score == 0 else 0
                                elif match.away == team:
                                    gs += result.away_score
                                    ga += result.home_score
                                    cs += 1 if result.home_score == 0 else 0
                                if result.result == "D":
                                    draw += 1
                                if (result.result == "H" and match.home == team) or (result.result == "A" and match.away == team ) :
                                    win += 1
                                if (result.result == "A" and match.home == team) or (result.result == "H" and match.away == team ) :
                                    lose += 1
                                    
                        except Exception as e:
                            print("Error ranking get_result", e)
                                                    
                    pts = win*3 + draw
                    ppg = round(pts / len(matchs), 2)
                    avg_gs = round(gs / len(matchs), 2) if gs > 0 else 0
                    avg_ga = round(ga / len(matchs), 2) if ga > 0 else 0
                                        
                    element = {
                        "team"    : team,
                        "mj"      : len(matchs),
                        "win"     : win,
                        "draw"    : draw,
                        "lose"    : lose,
                        "gs"      : gs,
                        "ga"      : ga,
                        "gd"      : gs - ga,
                        "form"     : [team.form(x) for x in matchs[:EditionTeam.NB]],
                        "pts"     : pts,
                        "ppg"     : ppg,
                        "cs"      : cs,
                        "btts"    : btts,
                        "avg_gs"  : avg_gs,
                        "avg_ga"  : avg_ga,
                        "p1_5"    : int(round(team.plus_but(1.5, date)/len(matchs), 2)*100),
                        "p2_5"    : int(round(team.plus_but(2.5, date)/len(matchs), 2)*100),
                        "m3_5"    : int(round(team.moins_but(3.5, date)/len(matchs), 2)*100),
                    }
                    element["form"].reverse()
                    datas.append(element)
            
            datas = sorted(datas, reverse=True, key=lambda x: (x.get("pts"), x.get("gd"), x.get("win")))
            return datas
        
        except Exception as e:
            print("Error ranking out", e)
    
    
    def series(self):
        matchs = self.edition_du_match.filter(is_finished = True).exclude(is_posted = True)
        series = []
        for match in matchs:
            result = match.get_result()
            if result is None:
                continue
            series.append(result.home_score + result.away_score)
        return series
    
    
    
    def cs(self):
        matchs = self.edition_du_match.filter(is_finished = True).exclude(is_posted = True)
        total, test = 0, 0
        for match in matchs:
            result = match.get_result()
            if result is None:
                continue
            if result.home_score == 0 or  result.away_score == 0:
                total +=1
        return total
    
    
    def half_cs(self):
        matchs = self.edition_du_match.filter(is_finished = True).exclude(is_posted = True)
        total, test = 0, 0
        for match in matchs:
            result = match.get_result()
            if result is None:
                continue
            if result.home_half_score is not None:
                if result.home_half_score == 0 or result.away_half_score == 0:
                    total +=1
        return total


    def btts(self):
        matchs = self.edition_du_match.filter(is_finished = True).exclude(is_posted = True)
        total, test = 0, 0
        for match in matchs:
            result = match.get_result()
            if result is None:
                continue
            if result.home_score > 0 and result.away_score > 0:
                total +=1
        return total
    
    
    def half_btts(self):
        matchs = self.edition_du_match.filter(is_finished = True).exclude(is_posted = True)
        total, test = 0, 0
        for match in matchs:
            result = match.get_result()
            if result is None:
                continue
            if result.home_half_score is not None:
                if result.home_half_score > 0 and  result.away_half_score > 0:
                    total +=1
        return total
    

    def nul_nul(self):
        matchs = self.edition_du_match.filter(is_finished = True).exclude(is_posted = True)
        total, test = 0, 0
        for match in matchs:
            result = match.get_result()
            if result is None:
                continue
            if result.home_score == 0 and result.away_score == 0:
                total +=1
        return total
    
    
    def half_nul_nul(self):
        matchs = self.edition_du_match.filter(is_finished = True).exclude(is_posted = True)
        total, test = 0, 0
        for match in matchs:
            result = match.get_result()
            if result is None:
                continue
            if result.home_half_score is not None:
                if result.home_half_score == 0 and  result.away_half_score == 0:
                    total +=1
        return total
    
    
    
    def avg_buts(self):
        matchs = self.edition_du_match.filter(is_finished = True).exclude(is_posted = True)
        total, test = 0, 0
        for match in matchs:
            result = match.get_result()
            if result is None:
                test += 1
                continue
            total += result.home_score + result.away_score
        return round(total / (len(matchs) - test), 2) if (len(matchs) - test) > 0 else 0
    
    
    def half_avg_buts(self):
        matchs = self.edition_du_match.filter(is_finished = True).exclude(is_posted = True)
        total, test = 0, 0
        for match in matchs:

competitionApp/routes.py
from .schemas import *
import graphene


class competitionAppQuery(object):
    search_pays                         = PaysType.ListField(action=graphene.String(default_value="search_pays"))
    search_type_competition             = TypeCompetitionType.ListField(action=graphene.String(default_value="search_type_competition"))
    search_competition                  = CompetitionType.ListField(action=graphene.String(default_value="search_competition"))
    search_edition                      = EditionType.ListField(action=graphene.String(default_value="search_edition"))
    search_edition_competition          = EditionCompetitionType.ListField(action=graphene.String(default_value="search_edition_competition"))
    search_ranking                      = RankingType.ListField(action=graphene.String(default_value="search_ranking"))
    search_ligne_ranking                = LigneRankingType.ListField(action=graphene.String(default_value="search_ligne_ranking"))
    search_competition_stat             = CompetitionStatType.ListField(action=graphene.String(default_value="search_competition_stat"))

    
class competitionAppMutation(object)    : 
    create_pays                         = PaysType.CreateField()
    update_pays                         = PaysType.UpdateField()
    
    create_type_competition             = TypeCompetitionType.CreateField()
    update_type_competition             = TypeCompetitionType.UpdateField()
    
    create_competition                  = CompetitionType.CreateField()
    update_competition                  = CompetitionType.UpdateField()
    
    create_edition                      = EditionType.CreateField()
    update_edition                      = EditionType.UpdateField()
    
    create_edition_competiton           = EditionCompetitionType.CreateField()
    update_edition_competiton           = EditionCompetitionType.UpdateField()
    
    create_ranking                      = RankingType.CreateField()
    update_ranking                      = RankingType.UpdateField()
    
    create_ligne_ranking                = LigneRankingType.CreateField()
    update_ligne_ranking                = LigneRankingType.UpdateField()
    
    create_competition_stat             = CompetitionStatType.CreateField()
    update_competition_stat             = CompetitionStatType.UpdateField()

competitionApp/views.py
from django.shortcuts import render, reverse
from competitionApp.models import *
from django.http import HttpResponseRedirect
from annoying.decorators import render_to
import statsApp.get_recherche_facts as get_recherche_facts
from datetime import datetime
# Create your views here.


@render_to("competitionApp/pays.html")
def pays(request):
    if request.method == "GET":
        pays = Pays.objects.all()
        ctx = {"pays" : pays}
        return ctx
    
        
@render_to("competitionApp/country.html")
def country(request, pays):
    if request.method == "GET":
        country = Pays.objects.get(name = pays)
        ctx = {"country" : country}
        return ctx
        
        
        
def competition(request, pays, competition):
    if request.method == "GET":
        competition = Competition.objects.get(pays__name = pays, name = competition)
        editions = competition.competition_edition.filter()
        edition = editions.first()
        return HttpResponseRedirect(reverse('competitionApp:competition_edition', args=[pays, competition.name, edition.edition]))
      
 
 
@render_to("competitionApp/competition.html")
def competition_edition(request, pays, competition, edition):
    if request.method == "GET":
        edition = EditionCompetition.objects.get(competition__pays__name = pays, competition__name = competition, edition__name = edition)
        competition = edition.competition
        editions = [] or competition.competition_edition.filter()
        matchs_played = edition.edition_du_match.filter(is_finished = True).exclude(is_posted = True).order_by('-date')
        next_matchs = edition.edition_du_match.filter(is_finished = False, date__gte = datetime.now())
        
        rank = edition.edition_rankings.filter().order_by('-date').first()
        
        teams = edition.edition_team.filter()
        total_official_matchs = (len(teams)-1) * len(teams)
        ratio = round(total_official_matchs / len(matchs_played) ) * 100
        
        facts = [] 
        # or get_recherche_facts.function(matchs)
        
        victoires = nuls = p1_5 = m3_5 = btts = cs = ht = ft = 0
        for x in matchs_played:
            result = x.get_result()
            if result.home_half_score is not None:
                ht += result.home_half_score + result.away_half_score
                ft += (result.home_score + result.away_score) - (result.home_half_score + result.away_half_score )
                
            if result.home_score != result.away_score:
                victoires += 1
            else :
                nuls += 1
                
            if result.home_score > 0 and result.away_score > 0:
                btts += 1
            else :
                cs += 1
                
            if result.home_score + result.away_score > 1.5:
                p1_5 += 1
            elif result.home_score + result.away_score < 3.5 :
                m3_5 += 1

        
        ctx = {
            "edition":edition,
            "editions":editions,
            "competition" : competition,
            "matchs": matchs_played, 
            "next_matchs": next_matchs, 
            "total_official_matchs": total_official_matchs,
            "teams":teams, 
            "facts":facts, 
            "rank":rank, 
            "matchs20":matchs_played[:20], 
            "ratio":ratio, 
            "victoires": victoires,
            "nuls": nuls,
            "p1_5": p1_5,
            "m3_5": m3_5,
            "btts": btts,
            "cs": cs,
            "ht": ht,
            "ft": ft,
            }
        return ctx
      

competitionApp/templates/competitionApp/country.html
{% extends "layout/base.html" %} 
{% load static %}


{% block main  %}

<div class="container white-bg">

    <div class="row m-b-lg m-t-lg">
        <div class="col-md-6">

            <div class="profile-image">
                <img src="{{country.flag}}" class="img-circle circle-border m-b-md" alt="profile">
            </div>
            <div class="profile-info">
                <div class="">
                    <div>
                        <h1 class="no-margins">{{country.name}}</h1>
                        <h4>Founder of Groupeq</h4>
                        <ul class="tag-list" style="padding: 0">
                            <li><a href=""><i class="fa fa-tag"></i> Stats</a></li>
                            <li><a href=""><i class="fa fa-tag"></i> Résultats</a></li>
                            <li><a href=""><i class="fa fa-tag"></i> Prochains Matchs (7)</a></li>
                            <li><a href=""><i class="fa fa-tag"></i> Clubs ({{ country.pays_du_team.filter | length }})</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <table class="table small m-b-xs">
                <tbody>
                <tr>
                    <td>
                        <strong>{{ country.pays_de_competition.filter | length }}</strong> Compétitions
                    </td>
                    <td>
                        <strong>{{ country.pays_du_team.filter | length }}</strong> Clubs proféssionnels
                    </td>

                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-3">
            <small>Sales in last 24h</small>
            <h2 class="no-margins">206 480</h2>
            <div id="sparkline1"></div>
        </div>


    </div>

</div>
    
{% endblock main %}

competitionApp/templates/competitionApp/pays.html
{% extends "layout/base.html" %} 
{% load static %}


{% block main  %}

<div class="container">

    <div class="row">
        {% for country in  pays %}
        <div class="col-lg-4">
            <div class="contact-box">
                <a href=# data-toggle="modal" data-target="#modal-{{ country.name }}" href="{% url 'competitionApp:country' country.name %}">
                <div class="col-sm-4">
                    <div class="text-center">
                        {% if country.flag %}
                            <img alt="image" class="img-responsive" src="{{ country.flag.url }}">
                            {% endif %}
                    </div>
                </div>
                <div class="col-sm-8">
                    <h3><strong>{{ country.name }}</strong></h3>
                    <address>
                        <h5>{{ country.pays_de_competition.filter | length }} compétition(s)</h5>
                    </address>
                </div>
                <div class="clearfix"></div>
                    </a>
            </div>
        </div>

        <div class="modal inmodal" id="modal-{{ country.name }}" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg mt-5">
                <div class="modal-content animated fadeIn">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title">Compétitions - {{ country.name }} </h4>
                        <small class="font-bold">Veuillez choisir la compétion que vous voulez voir </small>
                    </div>
                    <div class="modal-body">
                        
                        <div class="row justify-content-center">
                            {% for compet in  country.pays_de_competition.filter %}
                                <div class="col-sm-6 col-md-4 col-lg-3 m-b-md">
                                    <a href="{% url 'competitionApp:competition' country.name compet.name %}">
                                        <div class="text-center border-right">
                                            <img alt="image" src="{{ compet.logo.url }}" style="height: 150px; width: 150px;">
                                        <h2>{{ compet.name }}</h2>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>

        {% endfor %}


    </div>

</div>
    
{% endblock main %}